default:
  image: python:3.11
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build twine

stages:
  - build
  - test
  - publish
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

build-macos-job:
  stage: build
  tags:
    - macos
  script:
    - python -m build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

build-windows-job:
  stage: build
  tags:
    - windows
  script:
    - python -m build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  rules:
    - when: never

test-macos-job:
  stage: test
  tags:
    - macos
  script:
    - pip install pytest
    - pip install dist/*.whl
    - pytest

test-windows-job:
  stage: test
  tags:
    - windows
  script:
    - pip install pytest
    - pip install dist/*.whl
    - pytest
  rules:
    - when: never


#publish-package-job:
#  stage: publish
#  script:
#    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
#  rules:
##    - if: $CI_COMMIT_TAG
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

publish-pages-job:
  stage: deploy
  image: python:3.11
  tags:
    - windows
  script:
    - pip install .[docs]
    - python examples/convert_and_add_to_docs.py
    - zensical build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pip-cache/
  pages:
    publish: site

  rules:
    - when: never
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'


