[project]
name = "poreflow-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "nbconvert>=7.17.0",
    "pip>=26.0.1",
    "zensical>=0.0.23",
]
