[project]
site_name = "poreFlow Documentation"
site_url = "https://twhoekstra.github.io/poreFlow-docs/"
site_description = "Documentation for the poreFlow Python Package"
site_author = "Thijn Hoekstra"
copyright = "&copy; 2026 Cees Dekker Lab"
docs_dir = "docs"
site_dir = "site"
nav = [
    {"Home" = "index.md"},
    {"Getting Started" = [
        "getting-started/installation.md",
        "getting-started/introduction.md",
        "getting-started/overview.md",
        "getting-started/typical-workflow.md",
    ]},
    {"Examples" =  [
        {"Input/Output" = [
            "examples/loading-ont-data.md",
            "examples/loading-utube-data.md",
        ]},
        {"Event detection and filtering" = [
            "examples/full-ont-processing.md",
        ]}
    ]},
    {"Reference" = "reference/poreflow.md"},
     {"Implementation Details" = [
        "implementation-details/wishlist.md",
        "implementation-details/fast5-update.md",
        "implementation-details/labview-to-fast5-conversion.md",
    ]},
    {"Developers" = [
        "developers/introduction.md",
        "developers/installation.md",
        "developers/style-guide.md",
        "developers/ci-cd.md",
        "developers/building.md",
        "developers/publishing.md",
    ]},
    {"Authors" = "authors.md"}
]
extra_javascript = [
  "javascripts/mathjax.js",
  "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["poreflow/src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false



# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "deep purple"
accent = "green"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "deep purple"
accent = "green"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "deep purple"
accent = "green"

[project.theme.icon]
logo = "lucide/hexagon"

[project.theme]
favicon = "assets/favicon.ico"
features = [
    "navigation.instant",
    "navigation.tabs",
    "navigation.path",
    "navigation.footer",
    "content.code.copy",
]

[[project.extra.social]]
icon = "fontawesome/brands/gitlab"
link = "https://gitlab.tudelft.nl/xiuqichen/poreFlow"
name = "poreFlow on GitHub"

[[project.extra.social]]
icon = "lucide/flask-conical"
link = "https://ceesdekkerlab.nl/"
name = "Cees Dekker Lab on website"


[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]

[project.markdown_extensions.def_list]

[project.markdown_extensions.footnotes]


[project.markdown_extensions.tables]

[project.markdown_extensions.toc]
permalink = true
title = "On this page"
permalink_title = "Anchor link to this section for reference"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"

[project.markdown_extensions.pymdownx.caret]

[project.markdown_extensions.pymdownx.details]


[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.pymdownx.keys]

[project.markdown_extensions.pymdownx.mark]

[project.markdown_extensions.pymdownx.smartsymbols]

[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.critic]

